// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdvhodymzfwdzfeltmsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdmhvZHltemZ3ZHpmZWx0bXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MDAwMTksImV4cCI6MjA3ODk3NjAxOX0.asI9upCQ8JHJN87Wd8mB1tcatV0JEQhD7zHalWsD3-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});